### ISSUE TITLE
Pagination pagecontext module

### ISSUE THREAD

**Issue by john-henry** [madebyraygun/craft-fractal#3]
Hi @daltonrooney 

Would you be able to share what you have under `modules\pagecontext\Pagination` ?

I've been trying to recreate myself but have had no success yet

**Comment by daltonrooney** [comment]
@john-henry Are you using Sprig for pagination, or just static links?

**Comment by john-henry** [comment]
I usually use Sprig

**Comment by daltonrooney** [comment]
@john-henry I just [pushed an update](https://github.com/madebyraygun/craft-fractal/commit/42e17b9cc39b501404ad762a6bcda39d4290eba4) to the `dev` branch that includes our default `Pagination.php` module. I also updated `StoriesIndexContext` to use that module, and updated `pagination.twig` to match the context generated by `Patination.php` with slots for Sprig properties.

Just one caveat, I haven't tested on this Craft install yet because the CMS portion of this repo isn't fully built out yet. But this is the pattern we use on all our projects and should be correct or very close to working. If you have trouble from here, I'd be happy to do a remote VSCode session with you. 👍🏻

**Comment by john-henry** [comment]
Fantastic! thanks @daltonrooney

**Comment by daltonrooney** [comment]
Closed by https://github.com/madebyraygun/craft-fractal/commit/42e17b9cc39b501404ad762a6bcda39d4290eba4 and https://github.com/madebyraygun/craft-fractal/commit/19a044e604e6470c1c9878b8b9487df2d2acfc2a
